name: Android Apk - Build & Release

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'temurin'

            - name: Use Node.js 16.13.1
              uses: actions/setup-node@v3
              with:
                  node-version: '16.13.1'

            - name: Run Release Shell script
              if: startsWith(github.ref, 'refs/tags/release')
              run: |
                  sh prepare_release.sh

            - name: Run QA Shell script
              if: ${{ !startsWith(github.ref, 'refs/tags/release') }}
              run: |
                  sh prepare_qa.sh

            - name: Yarn Install, Build, (Test)
              run: |
                  yarn install --frozen-lockfile
                  yarn build
                  yarn bundle

            - name: Upload APK artifact
              uses: actions/upload-artifact@v3.1.0
              with:
                  name: app-signed-release.apk
                  path: android/app/build/outputs/apk/signed/release/app-signed-release.apk

            - name: Set outputs
              id: vars
              run: echo "::set-output name=datestamp::$(date '+%Y-%m-%d__%H-%M')"

            - name: Publish Apk to Github Release
              uses: marvinpinto/action-automatic-releases@latest
              if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/release')
              with:
                  title: 'Nepaltoday - ${{ steps.vars.outputs.datestamp }}'
                  prerelease: false
                  files: android/app/build/outputs/apk/signed/release/app-signed-release.apk
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: ${{ steps.vars.outputs.datestamp }}

            - uses: dev-drprasad/delete-older-releases@v0.2.0
              with:
                  keep_latest: 50
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish Android Bundle to Google Play Store
              uses: r0adkll/upload-google-play@v1.0.17
              if: startsWith(github.ref, 'refs/tags/release')
              with:
                  serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON_PLAIN_TEXT }}
                  packageName: 'com.siristechnology.nepaltodayapp'
                  releaseFiles: android/app/build/outputs/bundle/signedRelease/app-signed-release.aab
                  track: production
